NOISSUE - Update Groups service to use Typescript
absmach/sdk-js pull request #11
Opened 2024-04-02 08:38 UTC by Musilah

### What does this do?
This migrates the groups service from Javascript to Typescript.
### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
N/A
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2024-04-04 11:58 UTC, ianmuchyri commented on src/defs.ts
> +  metadata?: Record<string, string>
you are missing param children

```
Children    []*Group  `json:"children,omitempty"`
```

2024-04-05 07:20 UTC, dborovcanin requested changes

2024-04-05 07:20 UTC, dborovcanin commented on examples/groups.ts
> +const defaultUrl = 'http://localhost'
Extract the token to the constant so that examples can be run easily.

2024-04-05 07:46 UTC, ianmuchyri requested changes

2024-04-05 07:46 UTC, ianmuchyri commented on src/groups.ts
> +      const groupData: Group = await response.json()
```suggestion
      const group: Group = await response.json()
```

2024-04-05 07:46 UTC, ianmuchyri commented on src/groups.ts
> +      const groupData: Group = await response.json()
```suggestion
      const group: Group = await response.json()
```

2024-04-05 07:46 UTC, ianmuchyri commented on src/groups.ts
> +      const groupsData: GroupsPage = await response.json()
```suggestion
      const groupsPage: GroupsPage = await response.json()
```

2024-04-05 07:46 UTC, ianmuchyri commented on src/groups.ts
> +      const groupData: Permissions = await response.json()
```suggestion
      const permissions: Permissions = await response.json()
```

2024-04-05 07:46 UTC, ianmuchyri commented on src/groups.ts
> +      const groupData: Permissions = await response.json()
do the same for the rest. The variables should be self descriptive

2024-04-05 07:46 UTC, ianmuchyri commented on src/groups.ts
> +      const enableResponse: Response = { status: response.status, message: 'Group Enabled successfully' }
`Enable` and `Disable` for group return the group

2024-04-05 09:44 UTC, ianmuchyri requested changes

2024-04-05 09:44 UTC, ianmuchyri commented on src/groups.ts
> +      const groupData: Group = await response.json()
```suggestion
      const group: Group = await response.json()
```

2024-04-05 09:44 UTC, ianmuchyri commented on src/groups.ts
> +      const groupData: Group = await response.json()
check the rest in the page that are not changed

2024-04-05 10:55 UTC, ianmuchyri approved these changes
LGTM

2024-04-05 10:57 UTC, dborovcanin approved these changes

2024-04-05 10:57 UTC, merged