JSSDK-23- Update tests for bootstrap service
absmach/sdk-js pull request #37
Opened 2024-04-14 16:57 UTC by wambui-pixel

Pull request title should be `JSSDK-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Add tests for Boostrap Service
### Which issue(s) does this PR fix/relate to?
Resolves #23 
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality
n/a
### Have you included tests for your changes?
yes
### Did you document any new/modified functionality?
n/a
### Notes

2024-04-23 10:07 UTC, wambui-pixel commented
This has all Bootstrap tests except for secureBootstrap function.

2024-04-23 13:36 UTC, Musilah approved these changes

2024-04-23 13:36 UTC, Musilah commented on tests/bootstraps.test.ts
> +  // const bootstraps_url = "http://localhost:9019";
remove this comment here

2024-07-01 11:54 UTC, dborovcanin requested changes
Keep `Bootstrap` name, it's in sync with the rest of the codebase.

2024-07-01 12:00 UTC, dborovcanin approved these changes

2024-07-01 12:28 UTC, ianmuchyri approved these changes

2024-07-01 12:42 UTC, merged