NOISSUE: Add addusergroup functionality
absmach/sdk-js pull request #39
Opened 2024-04-15 07:12 UTC by wambui-pixel

Pull request title should be `JSSDK-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Add User Group Functionality to Channels.ts
### Which issue(s) does this PR fix/relate to?

Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality
n/a
### Have you included tests for your changes?
n/a
### Did you document any new/modified functionality?
n/a
### Notes

2024-04-15 07:27 UTC, Musilah commented on src/sdk.ts
> +import Bootstrap from './bootstrap'
No need for this in this PR.

2024-04-15 14:31 UTC, ianmuchyri requested changes

2024-04-15 14:36 UTC, ianmuchyri approved these changes
LGTM

2024-04-16 10:05 UTC, dborovcanin approved these changes

2024-04-16 10:07 UTC, merged