NOISSUE - Updating Things.ts
absmach/sdk-js pull request #9
Opened 2024-03-28 17:53 UTC by wambui-pixel

Pull request title should be `JSSDK-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do? Updating Things .ts

### Which issue(s) does this PR fix/relate to? NOISSUE

Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality
Migrating things.js to things.ts
### Have you included tests for your changes?
Yes
### Did you document any new/modified functionality?
Yes
### Notes

2024-04-03 17:23 UTC, Musilah requested changes

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +        ).toString(),
```suggestion
        new URL(
          `channels${chan.id}/things?${new URLSearchParams(
            stringParams
          ).toString()}`,
          this.thingsUrl
        ).toString(),
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +  public async ThingsGetAll (
Whats the difference between this and `GetAll`?

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +      method: 'post',
```suggestion
      method: 'POST',
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +      const thingData = await response.json()
```suggestion
      const thingData: Thing = await response.json()
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +     * @param {string} thing_id - Thing ID.
update the docstrings

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +  public async Update (thing: Thing, token: string): Promise<Thing> {
```suggestion
  public async UpdateThing (thing: Thing, token: string): Promise<Thing> {
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +      body: JSON.stringify(thing)
```suggestion
      body: JSON.stringify( {secret: thing.credentials?.secret} )
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +  public async IdentifyThing (thingKey: string): Promise<Thing> {
This should return a thingId in an `identifyThingResp` struct

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +        new URL(this.thingsEndpoint, this.thingsUrl).toString(),
```suggestion
        new URL('/identify', this.thingsUrl).toString(),
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +      const thingData: Permissions = await response.json()
match the promise to what you're returning here

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +     * @method Enable - Deletes a thing when provided with a valid token and thing ID.
Mismatch in the docstrings

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +  public async Things (
This is a repeat of the `ThingsGetAll` and `GetAll` functions

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +  public async Things (
Choose one and delete the rest

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +  ): Promise<Users> {
```suggestion
  ): Promise<UsersPage> {
```

2024-04-03 17:23 UTC, Musilah commented on src/things.ts
> +     * @param {string}
update these docstrings too

2024-04-03 18:32 UTC, Musilah requested changes

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +  ): Promise<any> {
```suggestion
  ): Promise<: Permissions> {
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +      method: 'post',
```suggestion
      method: 'DELETE',
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    // Lists users in a channel.
Update the docstrings.

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    // Connects multiple things to multiple channels.
Match the comments to the function.

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    // }
```suggestion
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    // Connects thing to channel.
Match the docstrings to the function here as well.

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +  ): Promise<Users> {
```suggestion
  ): Promise<UsersPage> {
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    const payload = { subject: thingId, object: channelId }
```suggestion
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +      body: JSON.stringify(payload)
```suggestion
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    channelsID: string,
```suggestion
    channelID: string,
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +      body: JSON.stringify(connIDs)
```suggestion
      body: JSON.stringify( { thing_id: thingID, channel_id: channelID } )
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    }
```suggestion
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +    }
```suggestion
```

2024-04-03 18:32 UTC, Musilah commented on src/channels.ts
> +      body: JSON.stringify(payload)
```suggestion
```

2024-04-03 18:32 UTC, Musilah commented on examples/things.ts
> +// // //Things.js examples.
```suggestion
// Things.js examples.
```

2024-04-03 18:32 UTC, Musilah commented on examples/things.ts
> +    'administrator',
```suggestion
    '<relation>',
```

2024-04-04 11:51 UTC, ianmuchyri requested changes

2024-04-04 11:51 UTC, ianmuchyri commented on src/users.ts
> +      console.log(response)
remove log

2024-04-04 11:51 UTC, ianmuchyri commented on src/sdk.ts
> +// import Groups from "./groups";
remove all the commented out code.

2024-04-04 11:51 UTC, ianmuchyri commented on src/defs.ts
> +  credentials?: {
a channel does not have credentials. 
Channel struct looks like this:
```
type Channel struct {
	ID          string     `json:"id,omitempty"`
	DomainID    string     `json:"domain_id,omitempty"`
	ParentID    string     `json:"parent_id,omitempty"`
	Name        string     `json:"name,omitempty"`
	Description string     `json:"description,omitempty"`
	Metadata    Metadata   `json:"metadata,omitempty"`
	Level       int        `json:"level,omitempty"`
	Path        string     `json:"path,omitempty"`
	Children    []*Channel `json:"children,omitempty"`
	CreatedAt   time.Time  `json:"created_at,omitempty"`
	UpdatedAt   time.Time  `json:"updated_at,omitempty"`
	Status      string     `json:"status,omitempty"`
	Permissions []string   `json:"permissions,omitempty"`
}

```

2024-04-04 11:51 UTC, ianmuchyri commented on src/defs.ts
> +  credentials?: {
refer to the go sdk for these items

2024-04-04 11:51 UTC, ianmuchyri commented on src/defs.ts
> +  createdAt?: string
Lets use snake case for these

2024-04-04 11:51 UTC, ianmuchyri commented on src/defs.ts
> -export interface PageRes {
why are you deleting this interface?

2024-04-04 11:51 UTC, ianmuchyri commented on src/channels.ts
> +      method: 'post',
Keep the method names in capital for all
```suggestion
      method: 'POST,
```

2024-04-04 11:51 UTC, ianmuchyri commented on src/channels.ts
> +      body: JSON.stringify(payload)
```suggestion
      body: JSON.stringify({ subject: thingId, object: channelId })
```

2024-04-05 13:23 UTC, ianmuchyri requested changes

2024-04-05 13:23 UTC, ianmuchyri commented on examples/channels.ts
> +      '<thingId>', '<thingId>'
```suggestion
      '<userId>', '<userId>'
```

2024-04-05 13:23 UTC, ianmuchyri commented on examples/channels.ts
> +      '<thingId>', '<thingId>'
```suggestion
      '<userId>', '<userId>'
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      body: JSON.stringify({ subject: thingId, object: channelId })
```suggestion
      body: JSON.stringify({ thing_id: thingId, channel_id: channelId })
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      body: JSON.stringify({ subject: thingId, object: channelId })
```suggestion
      body: JSON.stringify({ thing_id: thingId, channel_id: channelId })
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const usersData: GroupsPage = await response.json()
```suggestion
      const groupsPage: GroupsPage = await response.json()
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const channelData: Permissions = await response.json()
```suggestion
      const permissions: Permissions = await response.json()
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const channelData: Channel = await response.json()
```suggestion
      const enabledChannel: Channel = await response.json()
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const channelData: Channel = await response.json()
```suggestion
      const disabledChannel: Channel = await response.json()
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const channelData: Channel = await response.json()
```suggestion
      const updatedChannel: Channel = await response.json()
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const channelData: ChannelsPage = await response.json()
```suggestion
      const channels: ChannelsPage = await response.json()
```

2024-04-05 13:23 UTC, ianmuchyri commented on src/channels.ts
> +      const channelData: Channel = await response.json()
```suggestion
      const channel: Channel = await response.json()
```

2024-04-05 14:32 UTC, ianmuchyri approved these changes
LGTM

2024-04-05 15:36 UTC, dborovcanin approved these changes

2024-04-05 15:36 UTC, merged